### ISSUE TITLE
Startup code calls SystemInit() too early, and clears out global variables set by SystemInit()

### ISSUE THREAD

**Issue by cpq** [STMicroelectronics/cmsis_device_l4#2]
**Describe the set-up**
A simple bare metal code that uses gcc/startup_stm32l432xx.s and defines  SystemInit() which sets SystemCoreClock

**Describe the bug**
 * SystemInit() is called by the assembly code **BEFORE** relocating data and zeroing BSS. If SystemInit() sets variables like SystemCoreClock, then the assembly code **CLEARS IT**, then calls main(). Consequently, main() sees all global variables (like SystemCoreClock) which are set by SystemInit(), at their initial values.

https://github.com/STMicroelectronics/cmsis_device_l4/blob/be87fa0d6817337be09d7255cea5693ecdb2da8a/Source/Templates/gcc/startup_stm32l432xx.s#L65

**How To Reproduce**
Use Nucleo-L432KC. Install ARM GCC. Build and flash https://github.com/cpq/bare-metal-programming-guide/tree/main/templates/blinky/nucleo-l432kc

```sh
git clone https://github.com/cpq/bare-metal-programming-guide
cd bare-metal-programming-guide/templates/blinky/nucleo-l432kc
make clean flash
```

**Additional context**

NOTE: Assembly code for other ST lines, e.g. F4, calls SystemInit() **AFTER** data and BSS init, just before main(), and does not have this problem:

https://github.com/STMicroelectronics/cmsis_device_f4/blob/73273c20e85c6c57688f6106485a2e4f2592ddf9/Source/Templates/gcc/startup_stm32f429xx.s#L95-L99

Why L4 is different? Is it done intentionally? This is clearly a bug, since main() should see the same state SystemInit() left upon return.

**Screenshots**

The debug output shows the SystemCoreClock, which is 0. It must not be 0, since it is set in SystemInit().

```text
tick:  1000, CPU 0 MHz
tick:  2000, CPU 0 MHz
```

**Comment by TOUNSTM** [comment]
Hello @cpq,

There are at least two reasons to make SystemInit() called before initialization of data are performed in GCC startup code.

1. When using external memories, the memory should be initialized prior to any memory access otherwise the copy of the data segment initializes from flash to SRAM is not done which leads to critical system behavior.

2. The device normally starts with low speed clock and therefore it will take long time to initialize the data and to startup the system from reset.

This fix will be integrated in all our series even for STM32CubeF4 it will be available in the frame of a next release. Please allow me to close this thread. Thank you for your comprehension. We are looking forward to reading from you again.

With regards,

**Comment by cpq** [comment]
@TOUNSTM thank you.

I noticed that other lines have this issue - like, a newer STM32G line.
Will all they be fixed - I mean, is there the same group handling all lines?
Or, the issue should be reported separately to every line?

**Comment by TOUNSTM** [comment]
Hello @cpq,

Actually, the point you raised has already been dealt and fixed internally. For each series, the fix will be made available as part of a future release.

With regards,

**Comment by cpq** [comment]
@TOUNSTM

Why did you close the issue, despite nothing has been done, and the issue is serious? Your code messes up with the user-defined variables.
And note, F4 line has the order correct, so your arguments for some reason do not apply for F4 CMSIS. Why do they apply to L4?
